"use client";

import { useEffect, useState, use } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import { motion } from "framer-motion";
import { toast } from "sonner";
import { Clock, DollarSign, CalendarDays, Loader2, CreditCard, AlertTriangle } from "lucide-react";

import api from "@/lib/api";
import { useAuthStore } from "@/lib/store";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { Separator } from "@/components/ui/separator";

import { DatePicker } from "@/components/date-picker";
import { TimePicker } from "@/components/time-picker";

interface Service {
  _id: string;
  name: string;
  description: string;
  price: number;
  duration: number;
  image?: string;
  category?: string;
}

export default function ServiceDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const resolvedParams = use(params);
  const router = useRouter();
  const { isAuthenticated } = useAuthStore();

  const [service, setService] = useState<Service | null>(null);
  const [loading, setLoading] = useState(true);
  const [bookingLoading, setBookingLoading] = useState(false);
  const [date, setDate] = useState<Date | undefined>(undefined);
  const [timeSlot, setTimeSlot] = useState("09:00 AM");

  const isDev = process.env.NODE_ENV === 'development';

  useEffect(() => {
    const fetchService = async () => {
      try {
        const res = await api.get(`/services/${resolvedParams.id}`);
        if (res.data.success) {
          setService(res.data.data);
        }
      } catch (error) {
        toast.error("Failed to load service details");
        router.push("/services");
      } finally {
        setLoading(false);
      }
    };
    fetchService();
  }, [resolvedParams.id, router]);

  const handleBook = async () => {
    if (!isAuthenticated) {
      toast.info("Please log in to book a service");
      router.push("/login");
      return;
    }

    if (!date || !timeSlot) {
      toast.error("Please select a date and time slot");
      return;
    }

    try {
      setBookingLoading(true);
      const res = await api.post("/bookings", {
        serviceId: resolvedParams.id,
        bookingDate: date.toISOString().split('T')[0],
        timeSlot
      });

      if (res.data.success && res.data.data.checkoutUrl) {
        // Redirect to Stripe Checkout Session URL generated by backend
        window.location.href = res.data.data.checkoutUrl;
      }
    } catch (error: unknown) {
      const errorMessage = error instanceof Error ? error.message : "Booking creation failed";
      toast.error(errorMessage);
      setBookingLoading(false);
    }
  };

  const hasValidImage = (img?: string) => img && img !== 'default-service.jpg' && (img.startsWith('/') || img.startsWith('http'));

  if (loading) {
    return (
      <div className="container mx-auto px-4 py-12 max-w-4xl min-h-screen">
        <Skeleton className="h-12 w-3/4 mb-4" />
        <Skeleton className="h-6 w-1/4 mb-8" />
        <Skeleton className="h-[200px] w-full mb-8" />
        <Skeleton className="h-12 w-full max-w-md mx-auto" />
      </div>
    );
  }

  if (!service) return null;

  return (
    <div className="container mx-auto px-4 py-12 max-w-4xl min-h-screen">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="bg-card rounded-3xl p-8 md:p-12 border shadow-xl shadow-primary/5 overflow-hidden relative"
      >
        {hasValidImage(service.image) && (
          <div className="absolute top-0 left-0 w-full h-64 md:h-80 -z-10 bg-muted">
            <Image
              src={service.image!}
              alt={service.name}
              fill
              className="object-cover opacity-20"
            />
            <div className="absolute inset-0 bg-gradient-to-b from-card/30 via-card/80 to-card" />
          </div>
        )}
        <div className="flex flex-col md:flex-row gap-12 justify-between items-start relative z-10">
          <div className="flex-1 space-y-6">
            <div className="inline-flex items-center rounded-full border border-primary/20 px-3 py-1 text-sm bg-primary/10 text-primary font-medium">
              {service.category || "Premium Service"}
            </div>
            <h1 className="text-3xl md:text-5xl font-bold tracking-tight">
              {service.name}
            </h1>

            <div className="flex flex-wrap gap-6 text-muted-foreground text-lg">
              <span className="flex items-center gap-2">
                <DollarSign className="w-5 h-5 text-primary" />
                <span className="font-semibold text-foreground">${service.price}</span>
              </span>
              <span className="flex items-center gap-2">
                <Clock className="w-5 h-5 text-primary" />
                <span>{service.duration} Minutes</span>
              </span>
              <span className="flex items-center gap-2">
                <CalendarDays className="w-5 h-5 text-primary" />
                <span>Available Today</span>
              </span>
            </div>

            <Separator className="my-8" />

            <div>
              <h3 className="text-xl font-semibold mb-4">Service Description</h3>
              <p className="text-lg text-muted-foreground leading-relaxed whitespace-pre-line">
                {service.description}
              </p>
            </div>
          </div>

          <div className="w-full md:w-[350px] bg-muted/30 p-6 rounded-2xl border sticky top-24">
            <h3 className="text-2xl font-bold mb-2">${service.price}</h3>
            <p className="text-muted-foreground mb-6">One-time payment</p>

            <div className="space-y-6 mb-8">
              <div className="space-y-2">
                <label className="text-sm font-semibold text-foreground/80 px-1">Select Date</label>
                <DatePicker date={date} setDate={setDate} />
              </div>

              <div className="space-y-3">
                <label className="text-sm font-semibold text-foreground/80 px-1 uppercase tracking-wider text-[10px]">Select Time Slot</label>
                <TimePicker value={timeSlot} onChange={setTimeSlot} />
              </div>
            </div>

            <Button
              size="lg"
              className="w-full text-lg h-14 shadow-md shadow-primary/20 hover:shadow-lg hover:shadow-primary/30 transition-all"
              onClick={handleBook}
              disabled={bookingLoading}
            >
              {bookingLoading ? (
                <>
                  <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                  Processing...
                </>
              ) : (
                <>
                  <CreditCard className="mr-2 h-5 w-5" />
                  Book Now
                </>
              )}
            </Button>

            <p className="text-xs text-center text-muted-foreground mt-4">
              You won&apos;t be charged until you confirm details on the secure checkout page.
            </p>

            {/* Dev-only Stripe test card guide */}
            {isDev && (
              <div className="mt-6 p-4 rounded-xl bg-amber-500/10 border border-amber-500/20 text-xs space-y-2">
                <div className="flex items-center gap-2 font-semibold text-amber-600 dark:text-amber-400">
                  <AlertTriangle className="h-3.5 w-3.5" />
                  Dev: Stripe Test Cards
                </div>
                <div className="space-y-1 text-muted-foreground">
                  <p>✅ Success: <code className="bg-background/60 px-1.5 py-0.5 rounded font-mono text-[11px]">4242 4242 4242 4242</code></p>
                  <p>❌ Decline: <code className="bg-background/60 px-1.5 py-0.5 rounded font-mono text-[11px]">4000 0000 0000 0002</code></p>
                  <p>⚠️ 3DS Auth: <code className="bg-background/60 px-1.5 py-0.5 rounded font-mono text-[11px]">4000 0025 0000 3155</code></p>
                  <p className="pt-1 italic">Use any future exp date, any 3-digit CVC, any ZIP.</p>
                </div>
              </div>
            )}
          </div>
        </div>
      </motion.div>
    </div>
  );
}
